/*
 * Copyright 2021 SYMBOL
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Amount } from './Amount';
import { Cosignature } from './Cosignature';
import { EmbeddedTransaction } from './EmbeddedTransaction';
import { Hash256 } from './Hash256';
import { NetworkType } from './NetworkType';
import { PublicKey } from './PublicKey';
import { Serializer } from './Serializer';
import { Signature } from './Signature';
import { Timestamp } from './Timestamp';
import { TransactionType } from './TransactionType';
import { Utils } from './Utils';
import { EmbeddedTransactionHelper } from './EmbeddedTransactionHelper';

/**
 * Interface to create instances of AggregateCompleteTransactionV1
 */
export interface AggregateCompleteTransactionV1Params {
    /**
     * Entity's signature generated by the signing account.
     */
    signature: Signature;
    /**
     * Public key of the signer of the entity.
     */
    signerPublicKey: PublicKey;
    /**
     * Version of this structure.
     */
    version: number;
    /**
     * Network on which this entity was created.
     */
    network: NetworkType;
    /**
     * transaction type
     */
    type: TransactionType;
    /**
     * transaction fee
     */
    fee: Amount;
    /**
     * transaction deadline
     */
    deadline: Timestamp;
    /**
     * Hash of the aggregate's transaction.
     */
    transactionsHash: Hash256;
    /**
     * Embedded transaction data.
Transactions are variable-sized and the total payload size is in bytes.
Embedded transactions cannot be
     * aggregates.
     */
    transactions: EmbeddedTransaction[];
    /**
     * Cosignatures data.
Fills up remaining body space after transactions.
     */
    cosignatures: Cosignature[];
}

/**
 * Send transactions in batches to different accounts (V1, deprecated).
Use this transaction when all required signatures are available when the transaction is
 * created.
 */
export class AggregateCompleteTransactionV1 implements Serializer {
    /**
     * TRANSACTION_VERSION
     */
    public readonly TRANSACTION_VERSION = 1;
    /**
     * TRANSACTION_TYPE
     */
    public readonly TRANSACTION_TYPE = 16705;
    /**
     * Entity's signature generated by the signing account.
     */
    public readonly signature: Signature;
    /**
     * Public key of the signer of the entity.
     */
    public readonly signerPublicKey: PublicKey;
    /**
     * Version of this structure.
     */
    public readonly version: number;
    /**
     * Network on which this entity was created.
     */
    public readonly network: NetworkType;
    /**
     * transaction type
     */
    public readonly type: TransactionType;
    /**
     * transaction fee
     */
    public readonly fee: Amount;
    /**
     * transaction deadline
     */
    public readonly deadline: Timestamp;
    /**
     * Hash of the aggregate's transaction.
     */
    public readonly transactionsHash: Hash256;
    /**
     * Embedded transaction data.
Transactions are variable-sized and the total payload size is in bytes.
Embedded transactions cannot be
     * aggregates.
     */
    public readonly transactions: EmbeddedTransaction[];
    /**
     * Cosignatures data.
Fills up remaining body space after transactions.
     */
    public readonly cosignatures: Cosignature[];

    /**
     * Constructor
     * @param signature - Entity's signature generated by the signing account.
     * @param signerPublicKey - Public key of the signer of the entity.
     * @param version - Version of this structure.
     * @param network - Network on which this entity was created.
     * @param type - transaction type
     * @param fee - transaction fee
     * @param deadline - transaction deadline
     * @param transactionsHash - Hash of the aggregate's transaction.
     * @param transactions - Embedded transaction data.
Transactions are variable-sized and the total payload size is in bytes.
Embedded transactions cannot be
     * aggregates.
     * @param cosignatures - Cosignatures data.
Fills up remaining body space after transactions.
     */
    constructor({
        signature,
        signerPublicKey,
        version,
        network,
        type,
        fee,
        deadline,
        transactionsHash,
        transactions,
        cosignatures,
    }: AggregateCompleteTransactionV1Params) {
        this.signature = signature;
        this.signerPublicKey = signerPublicKey;
        this.version = version;
        this.network = network;
        this.type = type;
        this.fee = fee;
        this.deadline = deadline;
        this.transactionsHash = transactionsHash;
        this.transactions = transactions;
        this.cosignatures = cosignatures;
    }

    /**
     * Creates an instance of AggregateCompleteTransactionV1 from binary payload
     * @param payload - byte payload to use to serialize the object
     * @returns Creates an instance of AggregateCompleteTransactionV1 from binary payload
     */
    public static deserialize(payload: Uint8Array): AggregateCompleteTransactionV1 {
        const byteArray = Array.from(payload);
        const size = Utils.bufferToUint32(Uint8Array.from(byteArray));
        byteArray.splice(0, 4);
        Utils.bufferToUint32(Uint8Array.from(byteArray));
        byteArray.splice(0, 4);
        const signature = Signature.deserialize(Uint8Array.from(byteArray));
        byteArray.splice(0, signature.size);
        const signerPublicKey = PublicKey.deserialize(Uint8Array.from(byteArray));
        byteArray.splice(0, signerPublicKey.size);
        Utils.bufferToUint32(Uint8Array.from(byteArray));
        byteArray.splice(0, 4);
        const version = Utils.bufferToUint8(Uint8Array.from(byteArray));
        byteArray.splice(0, 1);
        const network = Utils.bufferToUint8(Uint8Array.from(byteArray));
        byteArray.splice(0, 1);
        const type = Utils.bufferToUint16(Uint8Array.from(byteArray));
        byteArray.splice(0, 2);
        const fee = Amount.deserialize(Uint8Array.from(byteArray));
        byteArray.splice(0, fee.size);
        const deadline = Timestamp.deserialize(Uint8Array.from(byteArray));
        byteArray.splice(0, deadline.size);
        const transactionsHash = Hash256.deserialize(Uint8Array.from(byteArray));
        byteArray.splice(0, transactionsHash.size);
        const payloadSize = Utils.bufferToUint32(Uint8Array.from(byteArray));
        byteArray.splice(0, 4);
        Utils.bufferToUint32(Uint8Array.from(byteArray));
        byteArray.splice(0, 4);
        const transactions: EmbeddedTransaction[] = Utils.deserializeRemaining(
            EmbeddedTransactionHelper.deserialize,
            Uint8Array.from(byteArray),
            payloadSize,
            8,
        );
        byteArray.splice(0, transactions.reduce((sum, c) => sum + Utils.getSizeWithPadding(c.size, 8), 0));
        const cosignatures: Cosignature[] = Utils.deserializeRemaining(
            Cosignature.deserialize,
            Uint8Array.from(byteArray),
            byteArray.length,
            0,
        );
        byteArray.splice(0, cosignatures.reduce((sum, c) => sum + Utils.getSizeWithPadding(c.size, 0), 0));
        return new AggregateCompleteTransactionV1({
            signature: signature,
            signerPublicKey: signerPublicKey,
            version: version,
            network: network,
            type: type,
            fee: fee,
            deadline: deadline,
            transactionsHash: transactionsHash,
            transactions: transactions,
            cosignatures: cosignatures,
        });
    }

    /**
     * Gets the size of the object
     * @returns Gets the size of the object
     */
    public get size(): number {
        let size = 0;
        size += 4; // size;
        size += 4; // verifiableEntityHeaderReserved_1;
        size += this.signature.size; // signature;
        size += this.signerPublicKey.size; // signerPublicKey;
        size += 4; // entityBodyReserved_1;
        size += 1; // version;
        size += 1; // network;
        size += 2; // type;
        size += this.fee.size; // fee;
        size += this.deadline.size; // deadline;
        size += this.transactionsHash.size; // transactionsHash;
        size += 4; // payloadSize;
        size += 4; // aggregateTransactionHeaderReserved_1;
        size += this.transactions.reduce((sum, c) => sum + Utils.getSizeWithPadding(c.size, 8), 0); // transactions;
        size += this.cosignatures.reduce((sum, c) => sum + Utils.getSizeWithPadding(c.size, 0), 0); // cosignatures;
        return size;
    }

    /**
     * Serializes an object to bytes
     * @returns Serializes an object to bytes
     */
    public serialize(): Uint8Array {
        let newArray = new Uint8Array();
        const sizeBytes = Utils.uint32ToBuffer(this.size);
        newArray = Utils.concatTypedArrays(newArray, sizeBytes);
        const verifiableEntityHeaderReserved_1Bytes = Utils.uint32ToBuffer(0);
        newArray = Utils.concatTypedArrays(newArray, verifiableEntityHeaderReserved_1Bytes);
        const signatureBytes = this.signature.serialize();
        newArray = Utils.concatTypedArrays(newArray, signatureBytes);
        const signerPublicKeyBytes = this.signerPublicKey.serialize();
        newArray = Utils.concatTypedArrays(newArray, signerPublicKeyBytes);
        const entityBodyReserved_1Bytes = Utils.uint32ToBuffer(0);
        newArray = Utils.concatTypedArrays(newArray, entityBodyReserved_1Bytes);
        const versionBytes = Utils.uint8ToBuffer(this.version);
        newArray = Utils.concatTypedArrays(newArray, versionBytes);
        const networkBytes = Utils.uint8ToBuffer(this.network);
        newArray = Utils.concatTypedArrays(newArray, networkBytes);
        const typeBytes = Utils.uint16ToBuffer(this.type);
        newArray = Utils.concatTypedArrays(newArray, typeBytes);
        const feeBytes = this.fee.serialize();
        newArray = Utils.concatTypedArrays(newArray, feeBytes);
        const deadlineBytes = this.deadline.serialize();
        newArray = Utils.concatTypedArrays(newArray, deadlineBytes);
        const transactionsHashBytes = this.transactionsHash.serialize();
        newArray = Utils.concatTypedArrays(newArray, transactionsHashBytes);
        const payloadSize = this.transactions.reduce((sum, c) => sum + Utils.getSizeWithPadding(c.size, 8), 0);
        const payloadSizeBytes = Utils.uint32ToBuffer(payloadSize);
        newArray = Utils.concatTypedArrays(newArray, payloadSizeBytes);
        const aggregateTransactionHeaderReserved_1Bytes = Utils.uint32ToBuffer(0);
        newArray = Utils.concatTypedArrays(newArray, aggregateTransactionHeaderReserved_1Bytes);
        const transactionsBytes = Utils.writeList(this.transactions, 8);
        newArray = Utils.concatTypedArrays(newArray, transactionsBytes);
        const cosignaturesBytes = Utils.writeList(this.cosignatures, 0);
        newArray = Utils.concatTypedArrays(newArray, cosignaturesBytes);
        return newArray;
    }
}
